### ISSUE TITLE
v6 Roadmap

### ISSUE THREAD

**Issue by RobertBolender** [Faithlife/styled-ui#378]
## v6 goals

- [x] Can be installed cleanly on top of v5
- [x] Can have multiple versions installed without conflicts (no global CSS files, etc)
- [x] Should be installed as a direct dependency rather than a peer dependency

## v6 roadmap

- [x] Refactor Listbox/Dropdown components to Listbox/Menu/Dropdown (see https://github.com/Faithlife/styled-ui/issues/411 @korbinancell)
- [x] Remove all references to any `styleOverrides` props, replacing the functionality with styled-system props
  - [x] Accordion (https://github.com/Faithlife/styled-ui/pull/391)
  - [x] DatePickerInput (https://github.com/Faithlife/styled-ui/pull/392)
  - [x] Dropdown (https://github.com/Faithlife/styled-ui/pull/379)
  - [x] FilesSection (https://github.com/Faithlife/styled-ui/pull/395)
  - [x] Input (https://github.com/Faithlife/styled-ui/pull/392)
  - [x] Listbox (https://github.com/Faithlife/styled-ui/pull/432, see also https://github.com/Faithlife/styled-ui/issues/411)
  - [x] ModalBackdrop (only used internally, not exported)
  - [x] ParameterSentence (https://github.com/Faithlife/styled-ui/pull/410)
  - [x] SimpleToast (https://github.com/Faithlife/styled-ui/pull/400)
  - [x] Slider (https://github.com/Faithlife/styled-ui/pull/404)
  - [x] Tab? (https://github.com/Faithlife/styled-ui/pull/409)
- [x] Remove all references to legacy `theme` props, replacing the functionality with our global styled-system theme
  - [x] Checkbox (https://github.com/Faithlife/styled-ui/pull/412)
  - [x] Helpbox (https://github.com/Faithlife/styled-ui/pull/414)
  - [x] LoadingSpinner (https://github.com/Faithlife/styled-ui/pull/415)
  - [x] Radio (https://github.com/Faithlife/styled-ui/pull/416)
  - [x] SimpleToast (https://github.com/Faithlife/styled-ui/pull/400)
- [x] Consider updating exported API for parent/child components
  Example pattern: `<Modal>`, `<Modal.Content>` instead of `<Modal>` and `<ModalContent>`
  - [x] Tabs (https://github.com/Faithlife/styled-ui/pull/417)
- [x] Consider using the ChildConfig API pattern for these components:
  - [x] Checkbox (https://github.com/Faithlife/styled-ui/pull/412)
  - [x] Radio (https://github.com/Faithlife/styled-ui/pull/416)
- [x] Update all other components to accept styled-system props
  - [x] Popover (https://github.com/Faithlife/styled-ui/pull/338)
- [x] Update Styled-Components to v5 (performance improvements with ~zero~ minimal breaking changes) (https://github.com/Faithlife/styled-ui/pull/420)
- [x] v6 PR with Breaking Changes (https://github.com/Faithlife/styled-ui/pull/413)
  - [x] Update ReactSelect to v3 (https://github.com/Faithlife/styled-ui/pull/384, https://github.com/Faithlife/styled-ui/pull/413)
  - [x] Remove all Bootstrap components
  - [x] Remove GroupSelector
  - [x] Remove Grid
  - [x] Remove FilePicker
  - [x] Remove ProductDrawer
  - [x] Rename `text-input-v2` exports to remove the confusing "v2" label.
  - [x] Remove all v5 components
- [x] Ship it! (completed 2021-01-14)

## Shortly after shipping v6

- Storybook / docs upgrade (draft PR https://github.com/Faithlife/styled-ui/pull/397)
- Jest unit tests with [React-Testing-Library](https://github.com/testing-library/react-testing-library)
  - Prefer to co-locate tests within component directories, such as `Button.jsx` and `Button.test.jsx` adjacent to each other.
  - Test that all components render without crashing
  - Test that all components can transition to all appropriate states without crashing (isOpen, isClosed, toggles, etc.)
  - Test that components can render without crashing even if rendered outside of a global theme provider

## Further down the road

- Visual Regression / Snapshot Testing (Still under internal discussion, considering Percy or jest-image-snapshot for visual regression testing)

**Comment by tywmick** [comment]
Is there a standard set of Styled System prop categories that we want all components to use? At the moment I'm only adding to each v6 component the Styled System categories that are directly needed to replace some functionality being removed from the v5 version.

**Comment by RobertBolender** [comment]
> Is there a standard set of Styled System prop categories that we want all components to use?

Not yet, although adding `common` and `typography` as appropriate as you suggested sounds like a good idea.

**Comment by RobertBolender** [comment]
Closed with #413
